### ISSUE TITLE
这个左滑然后导航条的左滑返回不生效了？怎么解决？

### ISSUE THREAD

**Issue by peilinghui** [fangjinfeng/FJSegmentedPager#2]

**Comment by fangjinfeng** [comment]
你的具体情况是怎样的，能否说得详细点，demo里面左滑返回时没问题的！

**Comment by fangjinfeng** [comment]
我知道你说得问题,我看一下啊！最近换工作！有点忙！

**Comment by fangjinfeng** [comment]
你那边的导航条是系统的导航条还是自定义的？

**Comment by fangjinfeng** [comment]
naviagtionController.interactivePopGestureRecognizer.delegate = self;让navigationController遵循这个代理就可以了！
